# #############################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
# #############################################################################
---
name: Test Kyverno Policies

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

env:
  VERSION: v1.10.1

jobs:
  kyverno-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Create Helm template
        run: |
            helm template nginx-root ./charts/nginx-root > chart-template.yaml

      - name: Download Kyverno CLI
        run: |
          curl -sLO https://github.com/kyverno/kyverno/releases/download/${{ env.VERSION }}/kyverno-cli_${{ env.VERSION }}_linux_x86_64.tar.gz
          tar -xf kyverno-cli_${{ env.VERSION }}_linux_x86_64.tar.gz
          ./kyverno version          

      - name: Test new resources against existing policies
        run: ./kyverno apply .github/kyverno-policies/require-run-as-nonroot.yaml -r chart-template.yaml

      #- name: Test pre-defined cases
      #  run: ./kyverno test tests/
